disabled_rules:
  - line_length
  - trailing_whitespace
  - todo
  - identifier_name

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - discouraged_optional_boolean
  - fatal_error_message
  - closure_spacing

included:
  - .

excluded:
  - Carthage
  - Pods
  - .build
  - build
  - DerivedData
  - .swiftpm

reporter: "xcode"
